# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
env:
  global:
    - TEST_BLACKLIST=moveit,moveit_ros,moveit_runtime,moveit_ros_perception  # mesh_filter_test fails due to broken Mesa OpenGL
  matrix:
    - ROS_DISTRO=melodic ROS_REPO=ros              TEST=clang-format
    - ROS_DISTRO=melodic ROS_REPO=ros
    - ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed
before_script:
  - git clone -q https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - .moveit_ci/travis.sh
