moveit_grasps:
  generator:
    # Other verbose stuff
    verbose: false

    # Show hand of generated grasps
    show_prefiltered_grasps: false
    show_prefiltered_grasps_speed: 0.01

    # Ideal grasp orientation (RPY)
    # This is used to compare against grasp candidates for orientation scoring
    ideal_grasp_orientation_rpy: [3.14, 0, 0]
    show_ideal_grasp_orientation: true

    # Grasp scoring weights: Finger and suction grippers both use these
    # TODO(mlautman): move weights to config_robot/*.yaml
    orientation_x_score_weight: 2.0
    orientation_y_score_weight: 2.0
    orientation_z_score_weight: 2.0
    translation_x_score_weight: 1.0
    translation_y_score_weight: 1.0
    translation_z_score_weight: 1.0

    ###########################
    ## finger gripper settings
    ###########################
    # Grasp scoring weights: finger grippers only
    depth_score_weight: 1.0
    width_score_weight: 1.0

    ###########################
    ## suction gripper settings
    ###########################
    # Visual debug options
    debug_top_grasps: false
    # Show suction gripper overhang
    show_grasp_overhang: false

    # Grasp scoring weights: Suction grippers only
    # Sometimes the suction gripper is larger than the object being grasped.
    # this weight penalizes suction gripper overhanging
    overhang_score_weight: 100.0

  filter:
    # Show summary statistics
    statistics_verbose: false
    # Visualize the planes used by the filter
    show_cutting_planes: false
    # Collision checking in verbose
    collision_verbose: false
    collision_verbose_speed: 0.01
    # Collision checking in verbose on second pass (after all failed)
    show_grasp_filter_collision_if_failed: true
    # Show post-filter arrows
    show_filtered_grasps: false
    # Show pose-filter arm ik solutions
    show_filtered_arm_solutions: false
    show_filtered_arm_solutions_pregrasp_speed: 0.25
    show_filtered_arm_solutions_speed: 0.5

  planner:
    # Cartesian planning
    statistics_verbose: false
    verbose_cartesian_filtering: false
    show_cartesian_waypoints: true
    collision_checking_verbose: false
